from typing import Any, Literal
from pydantic import BaseModel, ConfigDict


AllowedTypes = Literal["string", "number", "integer", "float", "boolean", "null"]


class ParameterField(BaseModel):
    """Represents the type definition of a specific parameter."""
    model_config = ConfigDict(extra='forbid')

    type: AllowedTypes


class FunctionDefinition(BaseModel):
    """Represents a single available function the LLM can call."""
    model_config = ConfigDict(extra='forbid')
    
    name: str
    description: str
    parameters: dict[str, ParameterField] 
    returns: ParameterField


class PromptItem(BaseModel):
    """Represents a single natural language prompt from the input file."""
    model_config = ConfigDict(extra="forbid")

    prompt: str


class FunctionCallResult(BaseModel):
    """Represents the validated, determinsitic output generated by the LLM."""
    model_config = ConfigDict(extra="forbid")

    prompt: str
    name: str
    parameters: dict[str, Any]
